// <auto-generated />
using System;
using App.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20240118220112_UpdateDb2")]
    partial class UpdateDb2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("App.Persistence.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CommentatorEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CommentatorEmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommentatorEmailAddress");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("App.Persistence.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerEmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerEmailAddress");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("App.Persistence.Models.User", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EmailAddress");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("App.Persistence.Models.Comment", b =>
                {
                    b.HasOne("App.Persistence.Models.User", "Commentator")
                        .WithMany("Comments")
                        .HasForeignKey("CommentatorEmailAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentator");
                });

            modelBuilder.Entity("App.Persistence.Models.Media", b =>
                {
                    b.HasOne("App.Persistence.Models.User", "Owner")
                        .WithMany("Uploads")
                        .HasForeignKey("OwnerEmailAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("App.Persistence.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
